TheWorld/src/TheWorld/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TheWorld.ViewModels
{
    public class ContactViewModel
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(4096, MinimumLength = 10)]
        public string Message { get; set; }
    }
}

TheWorld/src/TheWorld/Controllers/Web/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheWorld.ViewModels;
using TheWorld.Services;
using Microsoft.Extensions.Configuration;

namespace TheWorld.Controllers.Web
{
    public class AppController : Controller
    {
        private IMailService _mailService;
        private IConfigurationRoot _config;

        public AppController(IMailService mailService, IConfigurationRoot config)
        {
            _mailService = mailService;
            _config = config;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (model.Email.Contains("aol.com"))
            {
                ModelState.AddModelError("", "We don't support AOL Addresses");
            }

            if (ModelState.IsValid)
            {
                _mailService.SendMail(_config["MailSettings:ToAddress"], model.Email, "From TheWorld", model.Message);

                ModelState.Clear();

                ViewBag.UserMessage = "Message Sent";
            }

            return View();
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

TheWorld/src/TheWorld/Views/App/About.cshtml
@{
    ViewBag.Title = "About Page";
}

<h2>
    About The World
</h2>

TheWorld/src/TheWorld/Views/App/Contact.cshtml
@model TheWorld.ViewModels.ContactViewModel
@{
    ViewBag.Title = "Contact Page";
}

@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<h2>
    Contact Me
</h2>

<form method="post">
    <div asp-validation-summary="ModelOnly"></div>

    @if (ViewBag.UserMessage != null)
    {
        <div>@ViewBag.UserMessage</div>
    }

    <label asp-for="Name"></label>
    <input asp-for="Name" />
    <span asp-validation-for="Name"></span>

    <label asp-for="Email"> </label>
    <input type="email" asp-for="Email" />
    <span asp-validation-for="Email"></span>

    <label asp-for="Message"></label>
    <textarea cols="40" rows="4" asp-for="Message"></textarea>
    <span asp-validation-for="Message"></span>

    <div>
        <input type="submit" value="Send Message" />
    </div>
</form>

TheWorld/src/TheWorld/Views/App/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2>The World</h2>

<p>
    This will be a fun website soon!
</p>

<form>
    <div>
        <label>
            Date
        </label>

        <input />
    </div>

    <div>
        <label>
            Location
        </label>

        <input />
    </div>

    <div>
        <input type="submit" value="Add" />
    </div>
</form>

TheWorld/src/TheWorld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>The World - @ViewBag.Title</title>

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div id="sidebar">
        <img src="~/images/rayo3d_logo.jpg" alt="user_image" class="user_img" />

        <span id="username">Sam Hastings</span>

        <ul class="menu">
            <li class="active"><a asp-controller="App" asp-action="Index">Home</a></li>
            <li><a asp-controller="App" asp-action="About">About</a></li>
            <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
        </ul>
    </div>

    <div id="wrapper">
        <div id="main">
            <div>
                <button id="sidebarToggle">
                    Toggle Menu
                </button>
            </div>

            @RenderBody()
        </div>

        <div id="footer">
            &copy; 2016 The World Ltd.
        </div>
    </div>

    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("scripts", false)
    <script type="text/javascript" src="~/scripts/site.js"></script>
</body>
</html>